name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Reload PythonAnywhere Web App
        env:
          PA_USERNAME: ${{ secrets.USERNAME }}
          PA_TOKEN: ${{ secrets.TOKEN }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            "https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/$PA_USERNAME.pythonanywhere.com/reload/" \
            -H "Authorization: Token $PA_TOKEN")
          echo "Response code: $response"
          if [ "$response" -ne 200 ]; then
            echo "Reload failed!"
            exit 1
          fi
